#!/bin/bash
INPUT=/tmp/menu.sh.$$
OUTPUT=/tmp/output.sh.$$
trap "rm $OUTPUT; rm $INPUT; exit" SIGHUP SIGINT SIGTERM

#Gui interface by dialog to run other graphical interfaces created by David Smerkous and Eli Smith
#GNU pulblic license v2.0
#Currently mostly stable

function run_app(){

          OUTPUT2="/tmp/input.txt"
          >$OUTPUT2

          function runCommand() {
            local n=${@-"random"}
            run "$n" 2>&1 | dialog --title "Run" --backtitle "Run an Application" --progressbox 24 85
            dialog --title "Thanks" --ok-label "Return to menu" --clear --msgbox "Thanks for using Cri to run... ${n} If nothing pops up please make sure app is installed and extension is on" 13 35
          }

          trap "rm $OUTPUT2; exit" SIGHUP SIGINT SIGTERM
          dialog --title "Application" \
          --backtitle "Application Runner" \
          --inputbox "Enter the name of the application" 8 60 2>$OUTPUT2
          respose=$?
          name=$(<$OUTPUT2)
          case $respose in
            0)runCommand ${name};;
            1)echo "Exiting Application Runner";;
            255)echo "Exiting Application Runner"
          esac
          rm $OUTPUT2
}




function install_app(){
          OUTPUT3="/tmp/input2.txt"
          >$OUTPUT3

          function installCommand(){
            local n=${@-"random"}
            install $n 2>&1 | dialog --title "Install" --backtitle "Install an Application" --progressbox 24 85
          	dialog --title "Installed" --ok-label "Return to menu" --clear --msgbox "Thanks for using Cri to install... ${n}" 7 30
          }

          trap "rm $OUTPUT3; exit" SIGHUP SIGINT SIGTERM
          dialog --title "Application" \
          --backtitle "Application Installer" \
          --inputbox "Enter the name of the application" 8 60 2>$OUTPUT3
          respose=$?
          name=$(<$OUTPUT3)
          case $respose in
            0)installCommand ${name};;
            1)echo "Exiting Application Installer";;
            255)echo "Exiting Application Installer"
          esac
          rm $OUTPUT3
}

function files_app(){
	writer 'cd /root/+mkdir 2 2&>/dev/null'
	sleep 0.05
	sudo enter-chroot -b -u root xiwi runner
	sudo enter-chroot -b -u root xiwi thunar 2&>/dev/null
	dialog --title "File Manager" --ok-label "Return to menu" --clear --msgbox "Attempted to run file manager.. Give me a couple of seconds" 7 30
}


function remove_app(){
          OUTPUT4="/tmp/input3.txt"
          >$OUTPUT4
          function removeCommand(){
	          local n=${@-"random"}
	          remove $n 2>&1 | dialog --title "Remove" --backtitle "Remove an Application" --progressbox 24 85
	          dialog --title "Removed" --ok-label "Return to menu" --clear --msgbox "Thanks for using Cri to remove... ${n}" 7 30
          }
          trap "rm $OUTPUT4; exit" SIGHUP SIGINT SIGTERM
          dialog --title "Application" \
          --backtitle "Application Remover" \
          --inputbox "Enter the name of the application" 8 60 2>$OUTPUT4
          respose2=$?
          name2=$(<$OUTPUT4)
          case $respose2 in
            0)removeCommand ${name2};;
            1)echo "Exiting Application Remover";;
            255)echo "Exiting Application Remover"
          esac
          rm $OUTPUT4
}

function change_mode(){
  if [ ! -f ~/.dialogrc ]; then
    dialog --create-rc ~/.dialogrc
  else
    rm ~/.dialogrc
  fi
}

function updates(){
  updatecri gui 2>&1
  update 2>&1
}

function update_app(){
  updates 2>&1 | dialog --title "Update" --backtitle "Updater" --progressbox 24 85
  dialog --title "Updater" --ok-label "Return to menu" --clear --msgbox "Attempted to Update everything..." 7 30

}
function stop_app(){
  bash /usr/bin/stop
  dialog --title "Stop" --ok-label "Return to menu" --clear --msgbox "Attempted to Stop everything" 7 30
}

function acada_app(){
  dialog --clear --ok-label "Enter" --no-cancel --backtitle "Chrome gRaphical Interface Acada Package" \
  --title "[ Select Default Program ]" \
  --menu "Select and app to run" 17 60 8 \
  Netlogo "Modeling enviroment" \
  Hubnet "Netlogo(Client/Server)" \
  Arduino "Program an arduino" \
  Processing "Java visual arts" \
  LoggerPro "Graphs and data" \
  Energia "Program a launchpad" \
  Openshot "Video Editor" \
  Return "Return to menu" 2>"${INPUT}"
  menuitem=$(<"${INPUT}")
  case $menuitem in
    Netlogo) run netlogo 2>&1 | dialog --title "Netlogo" --backtitle "Running Netlogo" --progressbox 24 85;;
    Hubnet) run hubnet 2>&1 | dialog --title "Hubnet" --backtitle "Running Hubnet" --progressbox 24 85;;
    Arduino) run arduino 2>&1 | dialog --title "Arduino" --backtitle "Running Arduino" --progressbox 24 85;;
    Processing) run processing 2>&1 | dialog --title "Processing" --backtitle "Running Processing" --progressbox 24 85;;
    LoggerPro) run loggerpro 2>&1 | dialog --title "LoggerPro" --backtitle "Running LoggerPro" --progressbox 24 85;;
    Energia) run energia 2>&1 | dialog --title "Energia" --backtitle "Running Energia" --progressbox 24 85;;
    Openshot) run openshot 2>&1 | dialog --title "Open Shot" --backtitle "Running Open Shot" --progressbox 24 85;;
    Return) return 0;;
  esac
}

function search_app(){
          OUTPUT5="/tmp/input4.txt"
          INPUT5="/tmp/output5.txt"
          >$INPUT5
          >$OUTPUT5
           

          function searchCommand(){
          	local n=${@-"random"}
            search $n >$INPUT5
          	dialog --title "Results for ${n}" --ok-label "Return to menu" --clear --msgbox "$(<$INPUT5)" 30 95
          }
          
          trap "rm $OUTPUT5; exit" SIGHUP SIGINT SIGTERM
          dialog --title "Application" \
          --backtitle "Application Searching" \
          --inputbox "Enter a one or two word description of the app" 8 60 2>$OUTPUT5
          respose2=$?
          name2=$(<$OUTPUT5)
          case $respose2 in
            0)searchCommand ${name2};;
            1)echo "Exiting Application Searching";;
            255)echo "Exiting Application Searching"
          esac
          rm $OUTPUT5
          rm $INPUT5
}

while true; do
dialog --clear --ok-label "Enter" --no-cancel --backtitle "Chrome gRaphical Interface by David Smerkous and Eli Smith" \
--title "[ Select Option ]" \
--menu "You can use the mouse, UP/DOWN arrow keys, the first \n\
letter of the choice as a hot key, or the \n\
number keys to choose an option.\n\
 " 20 60 10 \
AcadaPkg "Acadapkg defaults" \
Run_app "Run an App" \
Install "Install an App" \
Remove "Remove an App" \
Search "Search App by context" \
Update "Update all Apps" \
Stop "Stop all Apps" \
Files "File Explorer" \
Color "Toggle color mode" \
Terminal "Go to Terminal" 2>"${INPUT}"
menuitem=$(<"${INPUT}")

case $menuitem in
  AcadaPkg) acada_app;;
  Run_app) run_app;;
  Install) install_app;;
  Remove) remove_app;;
  Search) search_app;;
  Update) update_app;;
  Stop) stop_app;;
  Files) files_app;;
  Color) change_mode;;
  Terminal) break;;
esac

done

[ -f $OUTPUT ] && rm $OUTPUT
[ -f $INPUT ] && rm $INPUT
clear

exit 0
