#!/bin/bash

#This is command args to run multi-line commands for crouton/cri

COMS=$@
mkdir ~/Downloads/.tmp 2>/dev/null
cd /home/chronos/user/Downloads/.tmp
echo "$COMS" | tr '[++]' '&&'>coms
exit 0
