#!/bin/bash
ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
        read -p "$1 [$prompt] " REPLY </dev/tty

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}
echo "Welcome to the academy package installer"
echo "The following software, should or soon to come to install"
echo "Arduino"
echo "4digits"
echo "lubuntu-software-center"
echo "netlogo"
echo "energia"
echo "jre (Openjdk)"
echo "gimp photo editor"
echo "Gdebi package installer"
echo "(We will also use our auto-configure in this installation)"
echo "File viewer"
echo "small-manager"
echo ""
echo ""
if ask "Would you like to install the academy package? (Double checking)"; then
    echo "Moving on..."
else
  exit
fi
echo ""
echo "Trying to fix the config file"
sudo enter-chroot -b -n precise cd /etc/crouton/ && sudo rm -rf xiwi.conf && sudo touch xiwi.conf
echo "Done..."
echo "Trying to install arduino core files"
sudo enter-chroot -b -n precise sudo apt-get -y install arduino-core
echo ""
echo "Done..."
echo ""
echo "Trying to install the graphical interface"
sudo enter-chroot -b -n precise sudo apt-get -y install arduino
echo ""
echo "Done..."

