#!/bin/bash
URL="https://raw.github.com/CodeBuds/Cri/master"
ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
        read -p "$1 [$prompt] " REPLY </dev/tty

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}
echo "Welcome to the academy package installer"
echo "The following software, should or soon to come to install"
echo "Arduino"
echo "4digits"
echo "lubuntu-software-center"
echo "netlogo"
echo "energia"
echo "jre (Openjdk)"
echo "gimp photo editor"
echo "Gdebi package installer"
echo "(We will also use our auto-configure in this installation)"
echo "File viewer"
echo "small-manager"
echo ""
echo ""
if ask "Would you like to install the academy package? (Double checking)"; then
    echo "Moving on..."
else
  exit
fi
echo ""
echo "Trying to fix the config file"
sudo enter-chroot -n precise cd /etc/crouton/ && sudo rm -rf xiwi.conf && sudo touch xiwi.conf
echo "Done..."
echo "Trying to install arduino core files"
sudo enter-chroot -n precise sudo apt-get -y install arduino-core
echo ""
echo "Done..."
echo ""
echo "Trying to install the graphical interface"
sudo enter-chroot -n precise sudo apt-get -y install arduino
echo ""
echo "Done..."
echo "Trying to install Gdebi package manager"
sudo enter-chroot -n precise sudo apt-get -y install gdebi
echo 
echo 
echo "Installing java"
sudo enter-chroot -n precise sudo apt-get -y install openjdk-7-jre
sudo enter-chroot -n precise sudo apt-get -y install curl
echo "Done now config for java 7..."
sudo enter-chroot -n precise sed -i '$ a\deb http://www.duinsoft.nl/pkg debs all' /etc/apt/sources.list && sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 5CB26B26 && sudo apt-get update && sudo apt-get install update-sun-jre 
echo "Installed java 7 (True version)..."
echo
echo
echo "Installing NetLogo..."
sudo enter-chroot -n precise cd /home/$(whoami)/Downloads && sudo wget https://ccl.northwestern.edu/netlogo/5.2.1/netlogo-5.2.1.tar.gz && tar xzf netlogo-5.2.1.tar.gz && rm netlogo-5.2.1.tar.gz && mv netlogo-5.2.1 /home/$(whoami)/netlogo
echo "Done..."
