#!/bin/bash
echo "Trying to fix the config file"
sudo enter-chroot -u root -n precise sudo rm -rf /etc/crouton/xiwi.conf
sudo enter-chroot -u root -n precise sudo touch /etc/crouton/xiwi.conf
echo "Config file fixed..."
