#!/bin/bash
echo "Trying to fix the config file"
sudo enter-chroot -b -n precise cd /etc/crouton/ && sudo rm -rf /etc/crouton/xiwi.conf && sudo touch /etc/crouton/xiwi.conf
echo "Config file fixed..."
