#!/bin/bash
NAME="$@"
echo "Trying to remove... $NAME"
writer "yes % apt-get remove $NAME" 2>&1
sudo enter-chroot -u root runner 2>&1
echo "
Done removing... $NAME"
sleep 5 # wait EOF for dialog
exit 0
