#!/bin/bash

ask() {				   #This is the function we call for our yes/no situations 
        read -p "$1?[y/n] " REPLY </dev/tty
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

part ()
{
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification 2>/dev/null | sed -n '9p' 2>/dev/null | sed -n -e 's/^.*titions //p' 2>/dev/null
}
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions $(part)
  sudo su -c "crossystem dev_boot_signed_only=0;mount -o remount,rw /"
  echo "If this is your second (Succesful) time running rootmount, you're done!
  Now please run wget -q -O - https://raw.github.com/CodeBuds/Cri/master/install2.sh | bash
  "
 if ask "We need to reboot is that okay"; then
    sudo reboot
 fi
  
