#!/bin/bash

ask() {				   #This is the function we call for our yes/no situations 
    while true; do
        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi
        read -p "$1 [$prompt] " REPLY </dev/tty
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

part ()
{
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification 2>/dev/null | sed -n '9p' 2>/dev/null | sed -n -e 's/^.*titions //p' 2>/dev/null
}
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions $(part)
  sudo crossystem dev_boot_signed_only=0
  sudo mount -o remount,rw /
  echo
  sleep 1
  echo "If this is your second (Succesful) time running rootmount, you're done!
  Now please run wget -q -O - https://raw.github.com/CodeBuds/Cri/master/install2.sh | bash
  "
  sleep 0.5
  echo
  sleep 0.5
  echo
  sleep 0.5
 if ask "Finished! Would you like to reboot now (HIGHLY RECCOMENDED!)(If no, you will need to later)?"; then
    sudo reboot
 fi
  
