#!/bin/bash
part ()
{
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification 2>/dev/null | sed -n '9p' 2>/dev/null | sed -n -e 's/^.*titions //p' 2>/dev/null
}
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions $(part)
  sudo crossystem dev_boot_signed_only=0
  sudo mount -o remount,rw /
  echo
  sleep 1
  echo "If this is your second (Succesful) time running rootmount, you're done!
  Now please run wget https://raw.github.com/CodeBuds/Cri/master/install2.sh | bash
  "
  sleep 0.5
  echo
  sleep 0.5
  echo
  sleep 0.5
 if ask "Finished! Would you like to reboot now (If no, you will need to later)?"; then
    sudo reboot
 fi
  
