#!/bin/bash
NAME=$@
echo "Trying to run $NAME..."
if [ "$NAME" = "e17" ]; then
    sudo start"$NAME"
else
    if [ "$NAME" != "e17" ]; then
        #sudo enter-chroot -b -u root xiwi $NAME
        DIR=/usr/bin
        if [ -f /usr/bin/$NAME ]; then
            DIR=/usr/bin
        else
            if [ -f /usr/games/$NAME ]; then
                DIR=/usr/games
            else
           	    if [ -f /usr/local/bin/$NAME ]; then
                    DIR=/usr/local/bin
                else
                    DIR=bin
                fi
           	
            fi
        fi
    case "$DIR" in
        bin) sudo enter-chroot -u root xiwi $DIR 2&>/dev/null
    esac
    writer "cd $DIR; xiwi ./$NAME &>/dev/null"
    sleep 0.01
    sudo enter-chroot -u root runner
    else
        echo "Sorry, didnt find $NAME on the list of installed programs
        If you believe you have this package, or want to install it
        Please run 'install $NAME'"
    fi
  
  echo "Thanks for using cri to run $NAME"
fi
