#!/bin/bash
NAME=$@
echo "Trying to run $NAME..."
ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
        read -p "$1 [$prompt] " REPLY </dev/tty

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}
if [[ "$NAME" = "e17"]]
then
    sudo start"$NAME"
else
    if [ "$NAME" = "xfce" ]
    then
        sudo startxfce4
    elif [ "$NAME" != "xfce" ]
    then
        echo "Turning debugging on..."
        sudo enter-chroot -u root xiwi $NAME
    else
        echo "Sorry, didnt find $NAME on the list of installed programs"
        echo "If you believe you have this package, or want to install it"
        echo "Please run 'install $NAME'"
    fi
  
  echo "Thanks for using cri to run $NAME"
fi
