#!/bin/bash
CTEMP=~/Downloads/.tmp
CBIN=/usr/bin
COMS=$1
EXTENSION=/home/chronos/user/Extensions/nhbmpbdladcchdhkemlojfjdknjadhmh
user=$(whoami)

ask() {
    while true; do
        read -p "$1 [$prompt] " REPLY </dev/tty
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

sure() {
    case "$1" in
        online*) return 1 ;;
        offline*) return 0 ;;
    esac
    return 0
}

if ask "Are you sure you want to completely remove Cri, xiwi, and crouton?"; then
    sudo chown chronos:chronos /mnt/stateful_partitions/crouton #Delets chroots
    sudo delete-chroot -a -y
    
    cd $CBIN #Deletes our bin files
    sudo rm -f $(cat /home/chronos/user/Downloads/.tmp/commands.txt | sed 's/.*\///g')
    # Restore the original crosh window icons
    if [ -d  $EXTENSION ]; then
    	echo "Installing icons..."
    	cd $EXTENSION/*/
    	sudo su -c "mv icon_128.png.bak icon_128.png;
    	mv icon_16.png.bak icon_16.png"
    fi
    
    cd $CBIN #Reinstalls a fresh version of Crosh
    if sure "$COMS"; then
        sudo su -c 'wget -q --no-check-certificate "https://raw.github.com/CodeBuds/Cri/master/Crosh" -O /usr/bin/criCrosh'
        if [ -s /usr/bin/criCrosh ]; then
            sudo su -c 'mv /usr/bin/criCrosh /usr/bin/crosh;chmod 755 /usr/bin/crosh'
            echo "Done..."
        else
            printf "File corrupted... Couldn't fully uninstall(Don't close this window)\n\nTry running this command\n\nuninstall offline\n"
        fi
    else
        sudo su -c 'mv /usr/bin/.crosh_backup /usr/bin/crosh'
        echo "Finished offline backup fix... Bye"
    fi
fi
unset CBIN
unset CTEMP
