#!/bin/bash
CBIN=/usr/bin
ARF="$@"
CLIB=/usr/lib64
URL="https://raw.github.com/CodeBuds/Cri/master"
CTEMP=~/Downloads/.tmp #DO NOT CHANGE THIS TO ~/DOWNLOADS, WANNA KNOW WHY, LOOK AT BOTTOM OF SCRIPT
CROUBIN=/mnt/stateful_partition/crouton/chroots/precise/usr/bin
cd $CTEMP 2&>/dev/null
wget -q --spider https://www.google.com
if [ $? != 0 ]; then
    echo "No internet connection detected. Please check your connection and run this again."
    exit 1
fi
cd $CBIN 2&>/dev/null

printf "Welcome to the cri updater, please give me a minute to organize everything\n\n"
if [ ! -z "$ARF" ]; then
    echo "Arguments: $ARF"
fi

ask() {
    while true; do
        read -p "$1 [$prompt] " REPLY </dev/tty
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

clean() {
    tput cuu 1 && tput el
}

lineCount() #Same function called earlier in the previous script to use in the counting of lines in commands.txt
{
    wc -l < commands.txt
}

lineCounttwo() #Same function called earlier in the previous script to use in the counting of lines in commands.txt
{
    wc -l < commands2.txt
}
lineCountlib() #Same function called earlier in the previous script to use in the counting of lines in commands.txt
{
    wc -l < libs.txt
}

if [ ! -d "$CTEMP" ]; then
    mkdir $CTEMP 2&> /dev/null
fi

cd $CTEMP 2&>/dev/null
PRINTS=""
if [ ! "$ARF" -eq "gui" ]; then
    PRINTS="..."
fi
printf "\nDownloading Cri files\n\n$PRINTS"
sudo wget -q --no-check-certificate "$URL/commands.txt" -O $CTEMP/commands.txt 2&>/dev/null #This is to download list of files needed
sudo chmod 755 commands.txt 2&>/dev/null #Makes the commands file have every permisson so that anyone can use it
NAMES="$(< commands.txt)" #names from names.txt file
LINES=$(lineCount)
NUMBERS=1
cd $CBIN 2&>/dev/null
for NAME in $NAMES; do #Downloads all nessisary files from github to /usr/local/bin
    if [ $ARF != gui ]; then
      clean
    fi
    echo "File $NUMBERS/$LINES$PRINTS"
    let "NUMBERS += 1"
    sudo wget -q --no-check-certificate "$URL/$NAME" -O $CBIN/${NAME##*/} 2&>/dev/null 
    sudo chmod 755 ${NAME##*/} 2&>/dev/null 
done

#This next chunk installs certain files directly into the chroot
cd $CTEMP 2&>/dev/null
printf "\nDownloading crouton files\n\n$PRINTS"
sudo wget -q --no-check-certificate "$URL/commands2.txt" -O $CTEMP/commands2.txt 2&>/dev/null #This is to download list of files needed
sudo chmod 755 commands2.txt 2&>/dev/null #Makes the commands file have every permisson so that anyone can use it

NAMES="$(< commands2.txt)" #names from names.txt file
LINES=$(lineCounttwo)
NUMBERS=1
cd /mnt/stateful_partition/crouton/chroots/*/usr/bin 2&>/dev/null
for NAME in $NAMES; do #Downloads all nessisary files from github to /usr/local/bin
    if [ $ARF != gui ]; then
      clean
    fi
    echo "File $NUMBERS/$LINES$PRINTS"
    let "NUMBERS += 1"
    sudo wget -q --no-check-certificate "$URL/$NAME" -O ${NAME##*/} 2&>/dev/null 
    sudo chmod 755 ${NAME##*/} 2&>/dev/null 
done

#This makes it so that whenever ctrl+alt+t is pressed, we launch directly into Cri
cd $CBIN 2&>/dev/null
sudo mv cri /usr/bin/crosh 2&>/dev/null # No need for backup if we are updating from a working version
echo "Done...
"
