#!/bin/bash
echo "Trying to fix permissions for X11"
read -p "Please enter your crouton username: " name
writer "chmod 755 /usr/bin/X11/Xorg+dpkg-reconfigure x11-common+chown $name /tmp"
sleep 0.5
sudo enter-chroot -u root runner
echo "I fixed the xiwi permissions"
#The above is just a double check
